/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InsuranceFinanceRole;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.InsuranceWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author VIRAJ
 */
public class InsuranceFinanceProcessRequest extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private InsuranceWorkRequest insuranceWorkRequest;

    /**
     * Creates new form InsuranceFinanceProcessRequest
     */
    InsuranceFinanceProcessRequest(JPanel userProcessContainer, UserAccount userAccount, InsuranceWorkRequest insuranceWorkRequest, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.insuranceWorkRequest = insuranceWorkRequest;
        txtPolicyNum.setText(insuranceWorkRequest.getPolicyId());
        txtSocialSecurity.setText(insuranceWorkRequest.getSsn());
        txtPolicyName.setText(insuranceWorkRequest.getPolicyName());
        txtAmountClaimed.setText(String.valueOf(insuranceWorkRequest.getAmountClaimed()));
        txtBillingAmt.setText(String.valueOf(insuranceWorkRequest.getAmountBilled()));
        txtCoveragePercent.setText(String.valueOf(insuranceWorkRequest.getInsuranceCustomer().getInsurance().getCoveragepercentage()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDisburseAmt = new javax.swing.JButton();
        btnRejectClaim = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtPolicyNum = new javax.swing.JTextField();
        txtPolicyName = new javax.swing.JTextField();
        lblPolicyName = new javax.swing.JLabel();
        txtBillingAmt = new javax.swing.JTextField();
        lblBillingAmt = new javax.swing.JLabel();
        txtAmountClaimed = new javax.swing.JTextField();
        lblAmountClaimed = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        txtSocialSecurity = new javax.swing.JTextField();
        lblCoverage = new javax.swing.JLabel();
        txtCoveragePercent = new javax.swing.JTextField();
        lblPhoto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        btnDisburseAmt.setBackground(new java.awt.Color(0, 153, 255));
        btnDisburseAmt.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnDisburseAmt.setText("Disburse Amount");
        btnDisburseAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisburseAmtActionPerformed(evt);
            }
        });
        add(btnDisburseAmt);
        btnDisburseAmt.setBounds(140, 350, 140, 32);

        btnRejectClaim.setBackground(new java.awt.Color(0, 153, 255));
        btnRejectClaim.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnRejectClaim.setText("Reject Claim");
        btnRejectClaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectClaimActionPerformed(evt);
            }
        });
        add(btnRejectClaim);
        btnRejectClaim.setBounds(300, 350, 120, 32);

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INSURANCE REQUEST PROCESS");
        add(jLabel3);
        jLabel3.setBounds(180, 30, 400, 29);

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Policy Number :");
        add(jLabel4);
        jLabel4.setBounds(120, 91, 120, 17);

        btnBack.setBackground(new java.awt.Color(0, 153, 255));
        btnBack.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(10, 23, 75, 29);

        txtPolicyNum.setEditable(false);
        add(txtPolicyNum);
        txtPolicyNum.setBounds(278, 86, 116, 23);

        txtPolicyName.setEditable(false);
        add(txtPolicyName);
        txtPolicyName.setBounds(278, 209, 116, 23);

        lblPolicyName.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblPolicyName.setForeground(new java.awt.Color(255, 0, 0));
        lblPolicyName.setText("Policy Name :");
        add(lblPolicyName);
        lblPolicyName.setBounds(132, 211, 110, 17);

        txtBillingAmt.setEditable(false);
        add(txtBillingAmt);
        txtBillingAmt.setBounds(278, 247, 116, 23);

        lblBillingAmt.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblBillingAmt.setForeground(new java.awt.Color(255, 0, 0));
        lblBillingAmt.setText("Billing Amount :");
        add(lblBillingAmt);
        lblBillingAmt.setBounds(110, 250, 120, 17);

        txtAmountClaimed.setEditable(false);
        txtAmountClaimed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountClaimedActionPerformed(evt);
            }
        });
        add(txtAmountClaimed);
        txtAmountClaimed.setBounds(278, 285, 116, 23);

        lblAmountClaimed.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblAmountClaimed.setForeground(new java.awt.Color(255, 0, 0));
        lblAmountClaimed.setText("Claim Amount :");
        add(lblAmountClaimed);
        lblAmountClaimed.setBounds(130, 290, 110, 17);

        lblSSN.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblSSN.setForeground(new java.awt.Color(255, 0, 0));
        lblSSN.setText("SSN :");
        add(lblSSN);
        lblSSN.setBounds(190, 130, 40, 17);

        txtSocialSecurity.setEditable(false);
        txtSocialSecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSocialSecurityActionPerformed(evt);
            }
        });
        add(txtSocialSecurity);
        txtSocialSecurity.setBounds(278, 124, 116, 23);

        lblCoverage.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblCoverage.setForeground(new java.awt.Color(255, 0, 0));
        lblCoverage.setText("Coverage% :");
        add(lblCoverage);
        lblCoverage.setBounds(150, 170, 90, 17);

        txtCoveragePercent.setEditable(false);
        add(txtCoveragePercent);
        txtCoveragePercent.setBounds(278, 171, 116, 23);

        lblPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insurance finance.gif"))); // NOI18N
        lblPhoto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblPhoto);
        lblPhoto.setBounds(0, 0, 720, 440);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisburseAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisburseAmtActionPerformed

        btnDisburseAmt.setEnabled(true);
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
        if (dialogResult == JOptionPane.YES_OPTION) {
            insuranceWorkRequest.setStatus("Insurance Claim Approved");
            JOptionPane.showMessageDialog(null, "Claim Approved Successfully!!!");
            btnDisburseAmt.setEnabled(false);
            btnRejectClaim.setEnabled(false);
        }
    }//GEN-LAST:event_btnDisburseAmtActionPerformed

    private void btnRejectClaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectClaimActionPerformed

        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
        if (dialogResult == JOptionPane.YES_OPTION) {
            insuranceWorkRequest.setStatus("Insurance Claim Rejected");
            btnRejectClaim.setEnabled(false);
            btnDisburseAmt.setEnabled(false);
        }

    }//GEN-LAST:event_btnRejectClaimActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        InsuranceFinanceWorkAreaJPanel iwjp = (InsuranceFinanceWorkAreaJPanel) component;
        iwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtAmountClaimedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountClaimedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountClaimedActionPerformed

    private void txtSocialSecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSocialSecurityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSocialSecurityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDisburseAmt;
    private javax.swing.JButton btnRejectClaim;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAmountClaimed;
    private javax.swing.JLabel lblBillingAmt;
    private javax.swing.JLabel lblCoverage;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPolicyName;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JTextField txtAmountClaimed;
    private javax.swing.JTextField txtBillingAmt;
    private javax.swing.JTextField txtCoveragePercent;
    private javax.swing.JTextField txtPolicyName;
    private javax.swing.JTextField txtPolicyNum;
    private javax.swing.JTextField txtSocialSecurity;
    // End of variables declaration//GEN-END:variables
}
