/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HealthcareAccountantRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.InsuranceCompanyEnterprise;
import Business.Insurance.Insurance;
import Business.InsuranceCustomer.InsuranceCustomer;
import Business.Network.Network;
import Business.Organization.AccountantOrganization;
import Business.Organization.InsuranceAgentOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AccountantBillingRequest;
import Business.WorkQueue.InsuranceWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DecimalFormat;
import java.util.List;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author VIRAJ
 */
public class AccountantProcessRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private AccountantOrganization accountantOrganization;
    private AccountantBillingRequest accountantBillingRequest;
    private EcoSystem ecosystem;
    private double amountToBePaid;

    /**
     * Creates new form AccountantWorkRequestJPanel
     */
    AccountantProcessRequestJPanel(JPanel userProcessContainer, UserAccount userAccount, AccountantBillingRequest request, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.accountantOrganization = accountantOrganization;
        this.accountantBillingRequest = request;
        this.ecosystem = ecoSystem;
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBillingRequestArea = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblBillAmount = new javax.swing.JLabel();
        lblPolicyName = new javax.swing.JLabel();
        lblAmountPayable = new javax.swing.JLabel();
        btnSendRequestForInsurance = new javax.swing.JButton();
        txtSSN = new javax.swing.JTextField();
        txtInsurancePolicyName = new javax.swing.JTextField();
        txtAmountPayable = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtBillAmount = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtPolicyNumber = new javax.swing.JTextField();
        lblPolicyNumber = new javax.swing.JLabel();
        lblAmountClaimed = new javax.swing.JLabel();
        txtAmountClaimed = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        btnCollectCash = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblBillingRequestArea.setBackground(new java.awt.Color(255, 255, 255));
        lblBillingRequestArea.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lblBillingRequestArea.setForeground(new java.awt.Color(204, 0, 0));
        lblBillingRequestArea.setText("BILLING REQUEST AREA");

        lblSSN.setBackground(new java.awt.Color(255, 255, 255));
        lblSSN.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblSSN.setText("SSN ID :");

        lblFirstName.setBackground(new java.awt.Color(255, 255, 255));
        lblFirstName.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblFirstName.setText("First Name :");

        lblLastName.setBackground(new java.awt.Color(255, 255, 255));
        lblLastName.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblLastName.setText("Last Name :");

        lblBillAmount.setBackground(new java.awt.Color(255, 255, 255));
        lblBillAmount.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblBillAmount.setText("Bill Amount :");

        lblPolicyName.setBackground(new java.awt.Color(255, 255, 255));
        lblPolicyName.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblPolicyName.setText("Insurance Policy Name :");

        lblAmountPayable.setBackground(new java.awt.Color(255, 255, 255));
        lblAmountPayable.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblAmountPayable.setText("Payable Amount :");

        btnSendRequestForInsurance.setBackground(new java.awt.Color(0, 153, 255));
        btnSendRequestForInsurance.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnSendRequestForInsurance.setText("Receive / Send request for Claim");
        btnSendRequestForInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestForInsuranceActionPerformed(evt);
            }
        });

        txtSSN.setEditable(false);

        txtInsurancePolicyName.setEditable(false);

        txtAmountPayable.setEditable(false);

        txtFirstName.setEditable(false);

        txtBillAmount.setEditable(false);

        txtLastName.setEditable(false);

        txtPolicyNumber.setEditable(false);

        lblPolicyNumber.setBackground(new java.awt.Color(255, 255, 255));
        lblPolicyNumber.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblPolicyNumber.setText("Policy Number :");

        lblAmountClaimed.setBackground(new java.awt.Color(255, 255, 255));
        lblAmountClaimed.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblAmountClaimed.setText("Amount to be Claimed :");

        txtAmountClaimed.setEditable(false);

        backJButton.setBackground(new java.awt.Color(0, 153, 255));
        backJButton.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        btnCollectCash.setBackground(new java.awt.Color(0, 153, 255));
        btnCollectCash.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnCollectCash.setText("Claim Full Amount From Patient");
        btnCollectCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollectCashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPolicyNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPolicyName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPolicyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInsurancePolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)
                        .addComponent(lblBillingRequestArea))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblLastName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFirstName, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblSSN, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAmountClaimed, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBillAmount, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAmountPayable, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAmountPayable, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBillAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAmountClaimed, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(btnSendRequestForInsurance)
                                .addGap(45, 45, 45)
                                .addComponent(btnCollectCash)))))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAmountClaimed, txtAmountPayable, txtBillAmount, txtFirstName, txtInsurancePolicyName, txtLastName, txtPolicyNumber, txtSSN});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBillingRequestArea))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPolicyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPolicyNumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInsurancePolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPolicyName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSSN)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstName)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastName)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBillAmount)
                            .addComponent(txtBillAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAmountClaimed)
                            .addComponent(txtAmountClaimed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAmountPayable)
                            .addComponent(txtAmountPayable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSendRequestForInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCollectCash, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAmountClaimed, txtAmountPayable, txtBillAmount, txtFirstName, txtInsurancePolicyName, txtLastName, txtPolicyNumber, txtSSN});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSendRequestForInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestForInsuranceActionPerformed
        String policyNumber = accountantBillingRequest.getPatient().getInsuranceCustomer().getInsurancePolicyNumber();
        String ssn = accountantBillingRequest.getPatient().getSsn();
        String policyName = accountantBillingRequest.getPatient().getInsuranceCustomer().getInsurance().getPolicyName();
        String insuranceCompany = accountantBillingRequest.getPatient().getInsuranceCustomer().getInsurance().getInsuranceCompanyName();
        double claimAmount = Double.parseDouble(txtAmountClaimed.getText());
        double billAmount = accountantBillingRequest.getBill();
        if (("Patient Transaction Completed").equals(accountantBillingRequest.getStatus())) {
            JOptionPane.showMessageDialog(null, "Insurance request sent for claim");
            return;
        }
        Insurance insurance = new Insurance(policyName, insuranceCompany, claimAmount);
        insurance.setCoveragepercentage(accountantBillingRequest.getPatient().getInsuranceCustomer().getInsurance().getCoveragepercentage());
        InsuranceCustomer insuranceCustomer = new InsuranceCustomer(policyNumber,insurance);
        insuranceCustomer.setFirstName(txtFirstName.getText().trim());
        insuranceCustomer.setLastName((txtLastName.getText().trim()));

        InsuranceWorkRequest insuranceWorkRequest = new InsuranceWorkRequest();
        insuranceWorkRequest.setInsuranceCompany(insuranceCompany);
        insuranceWorkRequest.setPolicyId(policyNumber);
        insuranceWorkRequest.setPolicyName(policyName);
        insuranceWorkRequest.setSsn(ssn);
        insuranceWorkRequest.setAmountClaimed(claimAmount);
        insuranceWorkRequest.setAmountBilled(billAmount);
        insuranceWorkRequest.setHealthCenter(enterprise.getName());

        insuranceWorkRequest.setSender(userAccount);
        insuranceWorkRequest.setStatus("Sent");
        insuranceWorkRequest.setInsuranceCustomer(insuranceCustomer);

        Organization org = null;
        InsuranceCompanyEnterprise matchedInsuranceCompany = null;

        List<Network> networks = ecosystem.getNetworks();
        for (Network network : networks) {
            List<Enterprise> enterprises = network.getEnterpriseDirectory().getEnterpriseList();
            for (Enterprise enterprise : enterprises) {
                if (enterprise.getName().equalsIgnoreCase(accountantBillingRequest.getPatient().getInsuranceCustomer().getInsurance().getInsuranceCompanyName())) {
                    matchedInsuranceCompany = (InsuranceCompanyEnterprise) enterprise;
                }
            }
        }

        for (Organization organization : matchedInsuranceCompany.getOrganizationDirectory().getOrganizations()) {
            if (organization instanceof InsuranceAgentOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequests().add(insuranceWorkRequest);
            userAccount.getWorkQueue().getWorkRequests().add(insuranceWorkRequest);
            accountantBillingRequest.setStatus("Patient Transaction Completed");
            accountantBillingRequest.getPatient().setIsTreatmentComplete(true);
            JOptionPane.showMessageDialog(null, "Money received from patient: " + String.format("%.2f", String.valueOf(amountToBePaid)) + ". Insurance Claim Request Raised Successfully for amount:" + claimAmount);
            btnSendRequestForInsurance.setEnabled(false);
        }


    }//GEN-LAST:event_btnSendRequestForInsuranceActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ProcessMedicalBillingsJPanel pmbjp = (ProcessMedicalBillingsJPanel) component;
        pmbjp.populateTable();
        pmbjp.populateInsuranceClaimTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnCollectCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollectCashActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("EmailBillingInformationToPatient", new EmailBillingInformationToPatient(userProcessContainer, accountantBillingRequest));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCollectCashActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnCollectCash;
    private javax.swing.JButton btnSendRequestForInsurance;
    private javax.swing.JLabel lblAmountClaimed;
    private javax.swing.JLabel lblAmountPayable;
    private javax.swing.JLabel lblBillAmount;
    private javax.swing.JLabel lblBillingRequestArea;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPolicyName;
    private javax.swing.JLabel lblPolicyNumber;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JTextField txtAmountClaimed;
    private javax.swing.JTextField txtAmountPayable;
    private javax.swing.JTextField txtBillAmount;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtInsurancePolicyName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPolicyNumber;
    private javax.swing.JTextField txtSSN;
    // End of variables declaration//GEN-END:variables

    private void populate() {
        String policyNumber = accountantBillingRequest.getPatient().getInsuranceCustomer().getInsurancePolicyNumber();
        DecimalFormat df2 = new DecimalFormat("#.##");
        double coverage = accountantBillingRequest.getPatient().getInsuranceCustomer().getInsurance().getCoveragepercentage();
        double billAmount = accountantBillingRequest.getBill();
        String ssn = accountantBillingRequest.getPatient().getSsn();
        String policyName = accountantBillingRequest.getPatient().getInsuranceCustomer().getInsurance().getPolicyName();
        String insuranceCompany = accountantBillingRequest.getPatient().getInsuranceCustomer().getInsurance().getInsuranceCompanyName();
        double claimAmount = (coverage * billAmount) / 100;
        amountToBePaid = billAmount - claimAmount;

        txtPolicyNumber.setText(policyNumber);
        txtSSN.setText(ssn);
        txtFirstName.setText(accountantBillingRequest.getPatient().getFirstName());
        txtLastName.setText(accountantBillingRequest.getPatient().getLastName());
        txtBillAmount.setText(String.valueOf(billAmount));
        txtInsurancePolicyName.setText(policyName);
        txtAmountClaimed.setText(String.valueOf(claimAmount));
        txtAmountPayable.setText(String.valueOf(df2.format(amountToBePaid)));

        if (claimAmount > 0) {
            btnSendRequestForInsurance.setEnabled(true);
            btnCollectCash.setEnabled(false);
        } else {
            btnCollectCash.setEnabled(true);
            btnSendRequestForInsurance.setEnabled(false);
        }

    }
}
